project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  site-url: https://places.volumen.ca
  favicon: favicon.ico
  title: "Places"
  navbar:
    right:
      - about.qmd
      - icon: rss
        href: index.xml
  back-to-top-navigation: true
  page-footer:
    left: 1999-2026 Places
    right: |
      Built with <a href="https://quarto.org"> Quarto {{< version >}}</a>
format:
  html:
    theme: cosmo #default journal cosmo litera sketchy
date-format: full
editor: visual

